### ISSUE TITLE
Image loading error

### ISSUE THREAD

**Issue by wdzhong** [liulu112601/Gated-Propagation-Net#3]
I got some error when trying to train the model. Then I tracked the error down and found out that some images in the `IMGS` folder cannot be loaded by the `torch.load()`. There images are:

> '437946.pth', '702829.pth', '712015.pth', '361729.pth', '58344.pth', '677819.pth', '440491.pth', '97924.pth', '704031.pth', '305447.pth', '536932.pth', '520655.pth', '203110.pth', '345018.pth', '753431.pth', '170128.pth', '102933.pth', '611343.pth', '605979.pth', '111363.pth', '158936.pth', '543164.pth', '75370.pth', '322952.pth', '163021.pth', '163573.pth', '261333.pth', '480977.pth', '316469.pth', '586088.pth', '720501.pth', '307863.pth', '8989.pth', '599650.pth', '725603.pth', '615416.pth', '546459.pth', '239115.pth', '657283.pth', '632738.pth', '80456.pth'

P.S. I use the preferred method to do the Dataset Extraction.

**Comment by liulu112601** [comment]
Hi, thx for the comment. Please update your PyTorch to 1.3.0., there are some bugs in the previous version.

**Comment by wdzhong** [comment]
> Hi, thx for the comment. Please update your PyTorch to 1.3.0., there are some bugs in the previous version.

Thanks for the quick reply! Not able to install the PyTorch 1.3.0 due to the cuda version. For now, I use numpy to save and load the images instead of PyTorch.
